### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ozgeekmum** [fontis/australia-mage2#1]
Heyo,

Not having much luck installing this.
Copied the files into app/code/Fontis/Australia
Ran the magento setup:upgrade but failing with 
 [Magento\Framework\Exception\LocalizedException]  
  Source class "\Fontis\CustomerGroupAccess\AccessCheck" for "Fontis\Customer  
  GroupAccess\AccessCheckFactory" generation does not exist.

This completely kills my local site - can't do any cli commands any more, or even login to the backend. 
Manually deleted all cache, pub/static.  
No luck.

This was a vanilla Magento2 instance.
Had used this deployment approach on two other branches with no problems. 

Any suggestions?

**Comment by chnorton** [comment]
Have you tried installing the extension through Composer? Magento 2 has specifically been designed for extensions to be installed (and updated) through Composer:

http://devdocs.magento.com/guides/v2.0/extension-dev-guide/intro/intro-composer.html

More information about how to install via Composer can be found on our website:

https://www.fontis.com.au/composer-faq

Could you try installing through Composer and let me know if you're still running into this issue?

**Comment by olibode** [comment]
Hi, I'm unable to install using composer on Magento 2.1 because of a dependency issues.

  Problem 1
    - Installation request for fontis/australia-mage2 0.2.0 -> satisfiable by fontis/australia-mage2[0.2.0].
    - fontis/australia-mage2 0.2.0 requires magento/module-checkout 100.0.\* -> no matching package found.

Magento 2.1 composer.json is
"magento/module-checkout": "100.1.0",

**Comment by sanker2008** [comment]
After runing command：
**composer require fontis/australia-mage2**

I got these：

> [InvalidArgumentException]  
>   Could not find package fontis/australia-mage2 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability   

After runing command：
**composer update**

I got these：

> Do not run Composer as root/super user! See https://getcomposer.org/root for details
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package magento/module-checkout could not be found in any version, there may be a typo in the package name.
>   Problem 2
>     - The requested package magento/module-directory could not be found in any version, there may be a typo in the package name.
>   Problem 3
>     - The requested package magento/module-payment could not be found in any version, there may be a typo in the package name.
>   Problem 4
>     - The requested package magento/module-store could not be found in any version, there may be a typo in the package name.
>   Problem 5
>     - The requested package magento/framework could not be found in any version, there may be a typo in the package name.
>   Problem 6
>     - Installation request for fontis/customergroupaccess-mage2 1.0.\* -> satisfiable by fontis/customergroupaccess-mage2[1.0.0].
>     - fontis/customergroupaccess-mage2 1.0.0 requires magento/framework 100.\* -> no matching package found.
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Any help？

**Comment by sanker2008** [comment]
Copy the code to:
app/code/Fontis/Australia
app/code/Fontis/CustomerGroupAccess

then I successed runing: php bin/magento setup:upgrade
the extension installed!
But I got error report when I open the cart page or checkout page:

> a:4:{i:0;s:37:"Object DOMDocument should be created.";i:1;s:13792:"#0 /var/www/html/mt2/200/vendor/magento/framework/View/Element/UiComponent/Config/Reader.php(95): Magento\Framework\View\Element\UiComponent\Config\DomMerger->getDom()
> #1 /var/www/html/mt2/200/vendor/magento/module-ui/Model/Manager.php(261): Magento\Framework\View\Element\UiComponent\Config\Reader->read()
> ...
> ..
> .

**Comment by brendanbell** [comment]
Hi,

Is this package compatible with Magento ver. 2.1.2

Regards
Brendan

**Comment by kartguru** [comment]
I too have really struggled to get this up and running. Has anyone successfully overcome some of these issues?

Cheers

**Comment by lloydhazlett** [comment]
@olibode @sanker2008 @brendanbell @kartguru Thank you all for letting us know of the problems you've encountered while installing the extension. I can confirm that we have identified a compatibility issue specifically with Magento 2.1 and we plan to release an update that should address it very soon.

**Comment by chnorton** [comment]
@olibode @sanker2008 @brendanbell @kartguru We've just pushed a new version, which updates the Composer module dependencies and should address the installation issue. Please give it a shot and let us know if there are any other problems.

**Comment by brendanbell** [comment]
Hi Chris,

Thanks for the update. I have the following magento version 2.1.2

I have run from shell the following
`composer require fontis/australia`

this returned the following

`Using version ^3.1 for fontis/australia
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing webshopapps/module-matrixrate (20.0.6)
Removing Webshopapps/Matrixrate
  - Removing symfony/stopwatch (v3.1.6)
  - Installing symfony/stopwatch (v3.1.5)
    Loading from cache

  - Removing symfony/process (v2.8.13)
  - Installing symfony/process (v2.8.12)
    Loading from cache

  - Removing symfony/finder (v3.1.6)
  - Installing symfony/finder (v3.1.5)
    Loading from cache

  - Removing symfony/filesystem (v2.8.13)
  - Installing symfony/filesystem (v2.8.12)
    Loading from cache

  - Removing symfony/event-dispatcher (v2.8.13)
  - Installing symfony/event-dispatcher (v2.8.12)
    Loading from cache

  - Removing fabpot/php-cs-fixer (v1.12.4)
  - Installing fabpot/php-cs-fixer (v1.12.2)
    Loading from cache

  - Removing seld/jsonlint (1.5.0)
  - Installing seld/jsonlint (1.4.1)
    Loading from cache

  - Removing phpunit/php-token-stream (1.4.9)
  - Installing phpunit/php-token-stream (1.4.8)
    Loading from cache

  - Removing sebastian/recursion-context (1.0.4)
  - Installing sebastian/recursion-context (1.0.2)
    Loading from cache

  - Removing sebastian/comparator (1.2.1)
  - Installing sebastian/comparator (1.2.0)
    Loading from cache

  - Removing symfony/config (v2.8.13)
  - Installing symfony/config (v2.8.12)
    Loading from cache

  - Removing symfony/dependency-injection (v2.8.13)
  - Installing symfony/dependency-injection (v2.8.12)
    Loading from cache

  - Removing symfony/yaml (v2.8.13)
  - Installing symfony/yaml (v2.8.12)
    Loading from cache

  - Installing fontis/composer-autoloader (2.0.3)
    Loading from cache

  - Installing guzzle/guzzle (v3.9.3)
    Loading from cache

  - Installing fontis/auspost-api-php (1.0.4)
    Loading from cache

  - Installing fontis/australia (3.1.6)
    Loading from cache
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Generating autoload files'

I then ran the following
`php magento setup:upgrade`

However I cannot see in the module list Fontis.

My question is this:
I created an account on fontis, do I need to update the composer.json file to reflect the 
"Authorization: Token xxx-xxxx-xxxxxxxxx--xxx-x-x-x-x"

thanks again for your work on this extension

Brendan

**Comment by chnorton** [comment]
@brendanbell Yes, you will need to add the Authorization config into your composer.json file. You will also need to add the Magento 2 version of the [Australia extension](https://www.fontis.com.au/australia-magento-extension) to your account to get access to it. After this you will be able to view the documentation for installing and setting it up.

The main thing is that the correct command to add it would be `composer require fontis/australia-mage2`.

Hope that helps!

**Comment by brendanbell** [comment]
Hi Chris,

1. Updated composer.json file (see attached text file)
2. Ran composer update
3. Placed an order for the fontis extension
4. ran composer require fontis/australia-mage2

Received the following error:

 [InvalidArgumentException]
  Could not find package fontis/australia-mage2 at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability

[composer.txt](https://github.com/fontis/australia-mage2/files/602654/composer.txt)

**Comment by brendanbell** [comment]
Just to add. 
I checked on https://packagist.org/search/?q=fontis

There is no package fontis/australia-mage2

brendan

**Comment by chnorton** [comment]
@brendanbell This looks to have been an issue on our end - would you mind trying again? You should be able to run `composer require fontis/australia-mage2` now and have it pick up that the extension is available.

**Comment by kartguru** [comment]
It appears to be working now for me though I haven't completed my dev site to process any orders.

Thanks for your help @chnorton and team
