### ISSUE TITLE
Issue in import CSV tablerate file for eParcel

### ISSUE THREAD

**Issue by ausl** [fontis/australia-mage2#2]
Hi there,

I have successfully installed the latest version and have an issue with import the tablerate for eParcel.

I exported the CSV file, and then made modification (tried all type of changes to the file (include not change at all)) and followed the guide for Magento 1 version.

However, every time i imported the modified CSV file, it shows 

"Something went wrong while saving this configuration: Eparcel import file is not readable"

Please Help!

Steven

**Comment by chnorton** [comment]
Hi Steven, would it be possible to link to a copy of a file which isn't working and the steps to reproduce the issue? That way we can test it ourselves and try and work out what's going wrong.

**Comment by ausl** [comment]
Hi Chris,

I think it is probably something to do with this file:

australia-mage2/Model/Config/Backend/Eparcel.php

I am not sure what is the reason behind it, i am just guessing whether the CSV file use the export function is not the same file format that can use for import.

I am running Magento 2.1.4 and used composer to install the latest version (0.3.2) of this extension, i am not sure what else information i can provide to you in respect to the issue. I tried re-install different version and access from different browser, but still cant resolve this issue.

Thanks

Steven

**Comment by alevashov** [comment]
Hi there

I experience this error (Magento CE 2.1.7) with your extension enabled if I try to do any changes in shipping methods in general, even in flat or table shipping.
Eparcel shipping is disabled, but seems that it tries to import a file any time you change and save shipping settings in Magento 2 admin.

Screenshot - http://easycaptures.com/fs/uploaded/1053/7115222658.jpg

**Comment by asriva** [comment]
Hi There, 
I am facing the similar issues as well. 
I am running the latest version of the M 2.xx. Has this been resolved?
