### ISSUE TITLE
Magento 2.3.2 comes with Australian states

### ISSUE THREAD

**Issue by solocommerce** [fontis/australia-mage2#21]
Hi

Just letting you know that I have found that Magento v2.3.2 comes with the Australian states/regions already included within the initial install. Looks like also added to Magento 2.2.8 https://github.com/magento/magento2/issues/17514

As a result, by installing the Australia-Mage2 module you will end up with duplicate states in any dropdown. 

As far as I can tell it looks like that only way to remove duplicate states is deleting via SQL?

Thanks

-Chad

**Comment by chnorton** [comment]
@solocommerce Thanks for raising this. We're aware of the problem and have been working on a solution that we hope to have released in the near future.

**Comment by solocommerce** [comment]
No problem, fantastic, would you like me to close this issue?

**Comment by chnorton** [comment]
This should now be addressed in version 1.0.6 (e6b8aced1fe6efa0f03da98e0baa34a8594d90f2) which has just been published.
