### ISSUE TITLE
Issue while installation

### ISSUE THREAD

**Issue by hemant2586** [fontis/australia-mage2#4]
I downloaded the package and trying to install it on dev server but it shows below error while installation:

[RuntimeException]
  Source class "\Fontis\CustomerGroupAccess\AccessCheck" for "Fontis\CustomerGroupAccess\AccessCheckFactory" generation does not exist.

Please help me to get it install.

**Comment by chnorton** [comment]
Sorry it's taken me a while to follow up on this. Could I just confirm that you're attempting to install the extension with Composer?

The error would seem to indicate that you're missing one of the dependencies, which would be automatically installed if you're using Composer.

**Comment by hemant2586** [comment]
Hello Chris,

Thanks for your response!

Yes there was dependency error. I didn't get the installation steps
properly at initial setup but got them and installed it via composer. It
was properly installed and working fine now.

Thanks for such a good extension.

Cheers!
Himmat

**Comment by chnorton** [comment]
Great to hear you got it sorted out.

**Comment by hussja** [comment]
HI Chnorton, I have to install this via ftp upload due to composer errors. error 
[RuntimeException]
Source class "\Fontis\CustomerGroupAccess\AccessCheck" for "Fontis\CustomerGroupAccess\AccessCheckFactory" generation does not exist.

Can you please shed some light.

**Comment by chnorton** [comment]
@hussja I'm not clear on whether you're saying that's an error before or after uploading it via FTP. I would certainly _not_ recommend deployment via FTP, and want to make it clear that the extension is only intended to be used with Composer so any issues using it should be addressed first.

What you've described sounds like a more general Magento deployment problem, so have you been able to deploy other extensions before?

**Comment by hussja** [comment]
Hi Chris, All good. Fixed the compiler and installed. 
Thanks for getting back to me and for making this extension available. ;)
