### ISSUE TITLE
No Aus Post Shipping

### ISSUE THREAD

**Issue by swordsreversed** [fontis/australia-mage2#6]
I don't get Aus Post in Config -> Sales ->Shipping Methods. I've reindexed and flushed the cache. Is there something else i need to do?

**Comment by chnorton** [comment]
Would you be able to run `php bin/magento module:status` and confirm that "Fontis_Australia" comes up in the "List of enabled modules" section? Could you also provide more information about how you installed the extension?

**Comment by swordsreversed** [comment]
So it came up in the disabled modules list. I ran module:enable and setup:upgrade (it asked me to) and now is in the shipping methods.

To install i followed the guide in the accounts section of your site:

> Installing
To add the extension to your website, run the following command from the Magento root (or wherever composer.json is located):
```
composer require fontis/australia-mage2
```

**Comment by chnorton** [comment]
Thanks, we'll look into updating the documentation with the full list of steps required to install a Magento 2 extension.
