### ISSUE TITLE
EcgM2:  The use of function basename() is forbidden

### ISSUE THREAD

**Issue by erfanimani** [fontis/australia-mage2#7]
```
FILE: australia-mage2/Controller/Adminhtml/Eparcel/ExportOrders.php
------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
------------------------------------------------------------------------------------
 90 | ERROR | The use of function basename() is forbidden
 90 | ERROR | The use of function basename() is forbidden
------------------------------------------------------------------------------------
```

More info here: https://magento.stackexchange.com/questions/144545/filesystem-best-practices

**Comment by chnorton** [comment]
This seems like a silly check, given that [basename doesn't even touch the file system](http://php.net/manual/en/function.basename.php). If you have any suggestions for ways to re-implement this functionality, we'd gladly review any PRs.

**Comment by erfanimani** [comment]
Thanks. Yeah, some of these checks seem silly. Especially since Magento themselves call basename like 80 times..
